### ISSUE TITLE
PcT Save Response

### ISSUE THREAD

**Issue by joynoug** [twcook/ccdgen-public#30]
Hi Tim,

One thing we believe would be important in the ccdgen's dashboard is a report of the PCT was done when save it.

Cheers, Joyce.

**Comment by twcook** [comment]
For 2.4.7 v1.0 We are deprecating the dashboard.  It will be removed in 2.4.7 v1.1  The admin UI has much better form validation and functionality now and there will not be any Public/paying users for the CCD-Gen for the foreseeable future.  During the deprecation period, the links have been removed but a user can add 'dashboard' to the URL and still use it.
